### ISSUE TITLE
About quality of detected VNTRs

### ISSUE THREAD

**Issue by Jesson-mark** [bcgsc/straglr#14]
Hi, @readmanchiu 

I'm currently wondering how to assess the quality of tandem repeats detected by `Straglr`. Since `Straglr` can report number of support reads for each TR, I wonder if a threshold could be applied to filter TRs whose number of support reads are below this threshold. If so, could you give any suggestions about how to choose this threshold? 

Thanks! 

Jesson-mark

**Comment by readmanchiu** [comment]
You can use min_support to set the threshold.
I usually set it to 5 for my work.

**Comment by Jesson-mark** [comment]
Thanks for your reply. I will have a try.
