### ISSUE TITLE
Straglr not finding TR's that are definitely present in targeted sequencing data 

### ISSUE THREAD

**Issue by AliSTaylor** [bcgsc/straglr#17]
Hello, 

I'm testing Straglr out on some data from targeted sequencing sources. We can find the repeat regions with other repeat measuring programs and by examining the fasta/bam files. However, when straglr is run, no errors are shown but the output files are empty. We have tried by aligning to whole chromosome and gene-specific references, attempted on two separate sources and continue to get the same results. 

Any help would be appreciated

**Comment by readmanchiu** [comment]
Thank you for trying Straglr and sorry to hear that nothing is output despite multiple efforts.
I guess just I will list my questions/suggestions in point form so it may be clearer:

1. Did you run it on ONT or PacBio sequences?
2. Does your alignment BAM file contain the read sequences?
3. Did you run it in genotyping mode (with `--loci` specfified with a bed file) or genome scan mode? Perhaps you can post the command you ran
4. The empty result could either be resulted from: A) Straglr cannot extract the "target" region subsequence from the reads; B) the `TRF` result may not be deemed "proper" to be reported by Straglr
5. For (A), it may happen with noisy ONT reads such that the boundary locations of the tentative repeat are not mapped in the alignment, hence Straglr fails to extract the sub-sequence. However, Straglr should output some warning messages indicating that it cannot extract sequences. 
6. For (B), the repeat sequence called by `TRF` does not span the majority of the extracted sub-sequence, suggesting the target locus contains more than the repeat, Straglr would chose not to report it.
7. You could try running with the `--debug` mode on, which would keep the temporary files. I wonder if could see if there is a `trf` output (a `.dat` file). If there is, it should mean read sequences were extracted (not scenario A) and more likely scenario B.

There may be other scenarios but this should help starting the detective work.

**Comment by readmanchiu** [comment]
Thanks for posting the error messages. In the error message started with `problem getting seq1` - the 4 items enclosed in the tuple after the read name should indicat the target locus: chromosome, start coordinate, end coordinate, and motif.
Why is "htt_50repeats" the chromosome here? I saw you provided "chr18.fa" for the reference parameter. Shouldn't "chr18" be the chromosome name? as for the start and end coordinates of `500` and `981`, are they genomic coordinates?

As for the errors started with `too_far_from_read_end`, I'm guessing by "altered the bed file by 495nt to attempt" you mean padding the target coordinates by 495. Please don't do that as the repeat reported by TRF has to be the majority of the sequence extracted from Straglr, i.e. if Straglr was told to extract the read sequence between A and B coordinates, and the TRF only detects a repeat between A+500, B-500, the result won't be deemed a positive one and ignored.

**Comment by AliSTaylor** [comment]
Hello, 

Apologies for the misunderstanding. I’m trying straglr on 2 separate datasets. One dataset uses chromosome 18 as a reference. The other uses a version of the HTT gene with 50 repeats. 

When assessing the samples aligned to the HTT gene, the coordinates are given relative to the reference sequence (i.e. 1-500) as the HTT repeat is close to the beginning of the gene. 

As to the second part, yes, I tried originally not padding the coordinates but for some reason, Straglr will not analyse the data with the original genomic coordinates.

**Comment by readmanchiu** [comment]
Let's focus on the one using genomic coordinates and genome alignments. When you ran with `--debug` on, did you get any error messages like `problem getting seq1`? 
Could it be the reference fasta you provided has difference chromsome names from the one you used for alignment? like one has a "chr" prefix and the other doesn't?
If the answer is no for the above, it is feasible to share a subset of your data to debug?

**Comment by AliSTaylor** [comment]
Attachment available until 16 Nov 2022
Hello, 

So no, they have the same chromosome name. I can’t attach that exact dataset. However, I have another dataset which we have published that I am experiencing the same issue with. It is a HTT dataset, which has been aligned to chromosome 4 which has genomic coordinates. It is PacBio data and results in empty files with no debugging information. I’ve attached it, along with the reference and the bed file. 
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAccDuXPDOJeZpDGbnrbRqs0xLRVjAeRvMz8VRDsTPe6Jv2MA1pfooDO8%2F%24%7Bf%7D%3Fo%3DAj1W3ETbGSU32TeJUaPkeLExSj9aN1VdMLrMvJEgH7Jh%26v%3D1%26x%3D3%26a%3DCAog4XVVtHgDdGDnChxNP3ncxS2ZjJHuUimJB-G0oU2SCIYSeBDe66W5vjAY3vugjcgwIgEAKgkC6AMA_z0wynVSBDEtFWNaBOigM7xqJsH9--qzOwJ3pGU3EZ8bAcclgxvWh5weH2TLZINJ6kTASs-9qwBxciY7ksY-N6EEw9ANNfJ5GVTVKp4-vQ8Gkh4w3XxGYfEumlc6xe5m2A%26e%3D1668622597%26fl%3D%26r%3DF765A839-0CD0-4147-8BAF-F9BD9EB9E984-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D6111D02E-88BC-49DF-A7A4-52B3D8109BDB%26p%3D49%26s%3Dg_xcKjUsTpA8MU1N3ycid5hDP4w&uk=fifWVEQ70KVBlm5RIm_eHA&f=straglr_htt.tar.gz&sz=58712918>straglr_htt.tar.gz
58.7 MB

**Comment by readmanchiu** [comment]
Great, thanks, will take a look and get back to you

**Comment by readmanchiu** [comment]
OK, looked at the linked BAM, the alignments have a lot of clipped bases at either or both ends of the reads, Straglr won't interrogate these kinds of mappings. It will handle soft-clips, but only for alignment pairs where both ends of the reads are mapped, i.e. it will handle cases where a long repeat in the middle of a read leads to 2 soft-clipped alignments, but the ends of the read must be confidently mapped.
The reads in this bam seems like kind of chimeric to me, where parts of the reads align to the same region multiple times. Of course I just cherry-picked some cases to look at, but that seems to be the reason why Straglr does not produce any report, because the alignments are all problematic.
