### ISSUE TITLE
Missing output

### ISSUE THREAD

**Issue by topochico-one** [bcgsc/straglr#21]
Thank you for creating Straglr! Does Straglr produce output for repeats whose length is equal to the reference? I am asking this because the output for some repeats seems to be missing.

**Comment by readmanchiu** [comment]
Thanks for trying Straglr!
If you run it in genotyping mode, it will size the loci given in the `--loci` bed file regardless of whether there is expansion.
If you run it in genome scan mode, which you don't provide a bed file of target loci, then it will just report loci that have sizes larger than the reference genome by a threshold specified by `--min_ins_size` (default=100bp)

If you still see missing anticipated loci in either mode and cannot understand why, please report and I am happy to follow up on it.
