### ISSUE TITLE
Problem with straglr_compare

### ISSUE THREAD

**Issue by gspirito** [bcgsc/straglr#26]
Hi, I would like to analyze WGS long-reads data of a trio (proband, mother and father) with straglr, but I encountered some problems with straglr_compare.

First I run straglr on the 3 bam files (aligned with minimap2) like so:
```
python3 straglr.py sample.bam ref.fasta sample_ID \
--exclude hg38_centromeres_telomeres_UCSC.bed \
--min_support 1 --min_ins_size 10 \
```
and got no errors or warnings.

Then I run 3 instances of straglr_compare:

The first time I ran:
`python3 ./straglr_compare.py proband.tsv mother.tsv proband_vs_mother.txt`
and got the proper result

Then I did:
`python3 ./straglr_compare.py proband.tsv father.tsv proband_vs_father.txt`
and got this error:
```
Traceback (most recent call last):
  File "/work/gspirito/software/straglr-master/straglr_compare.py", line 371, in <module>
    main()
  File "/work/gspirito/software/straglr-master/straglr_compare.py", line 359, in main
    vs_controls.append(vs_each_control(test_bed, control_bed, args.pval_cutoff, min_expansion=args.min_expansion, min_support=args.min_support, label=control_result))
  File "/work/gspirito/software/straglr-master/straglr_compare.py", line 147, in vs_each_control
    control_allele = float(control_cols[j-1])
ValueError: could not convert string to float: '.'
```

Finally I ran:
`python3 ./straglr_compare.py father.tsv mother.tsv father_vs_mother.txt`
and got no errors but no output file either.

Am I doing something wrong?
Is there a way to perform a 'proband vs mother+father' comparison?

Thanks in advance for the response.

Giovanni

**Comment by readmanchiu** [comment]
Thanks for your interest in the software, @gspirito 
Just wonder if you are using the latest release v1.4.1 or if you clone the repo and use the `straglr_compare.py` from the clone.
If you are using from your installation from v1.4.1, could you try to clone the repo and used the script from there?
I've made a few fixes to the script which I haven't put into a release yet.

**Comment by gspirito** [comment]
Hi, thank you for the response.

I tried both, 

this is the error i get with release 1.4.1:
```
  File "/work/gspirito/software/straglr/straglr_compare.py", line 374, in <module>
    main()
  File "/work/gspirito/software/straglr/straglr_compare.py", line 356, in main
    test_bed = parse_straglr_tsv(args.test, use_size=args.use_size, skip_chroms=args.skip_chroms, no_strand_version=args.no_strand_version)
  File "/work/gspirito/software/straglr/straglr_compare.py", line 65, in parse_straglr_tsv
    allele = '{:.1f}'.format(float(allele) / len(cols[3]))
```

this with cloning the repo:
```
Traceback (most recent call last):
  File "/work/gspirito/software/straglr-master/straglr_compare.py", line 371, in <module>
    main()
  File "/work/gspirito/software/straglr-master/straglr_compare.py", line 359, in main
    vs_controls.append(vs_each_control(test_bed, control_bed, args.pval_cutoff, min_expansion=args.min_expansion, min_support=args.min_support, label=control_result))
  File "/work/gspirito/software/straglr-master/straglr_compare.py", line 147, in vs_each_control
    control_allele = float(control_cols[j-1])
ValueError: could not convert string to float: '.'
```

**Comment by readmanchiu** [comment]
kind of puzzling because there is a check in the code to make sure the above error won't happen 
just want to make sure if your straglr output has the correct format, could you please run:
```
grep chrom <your_starglr_output> | awk '{print NF}'
```
to see if you have 15 columns in your output

**Comment by gspirito** [comment]
Hi, actually one of the output files does not have 15 columns:

```
grep chrom father.tsv | awk '{print NF}'
10
grep chrom proband.tsv | awk '{print NF}'
38
15
grep chrom mother.tsv | awk '{print NF}'
38
15

head father.tsv
#chrom	start	end	repeat	ref_size	test_allele	test_allele_support	expansion	control_alleles	pvals
chr1	2325103	2325243	TTCC	141.0	1601.9	3	704.0	897.9	4.97e-05
chr1	14554447	14554448	GATG	2.0	351.8	1	351.8	-	-
chr1	18528039	18528040	TA	2.0	433.0	1	433.0	-	-
chr1	19061313	19061499	CCA	187.0	1290.3	18	513.2	562.5,991.8	5.2e-35,1.96e-27
chr1	20309908	20309956	TG	49.0	243.0	1	217.9	25.1	4.96e-104
chr1	23484704	23484715	CCCT	12.0	120.0	1	120.0	-	-
chr1	38005776	38005777	CCTCC	2.0	471.2	1	471.2	-	-
chr1	40572636	40572637	AC	2.0	182.0	1	182.0	-	-
chr1	47134911	47134921	TCTGT	11.0	272.4	1	272.4	-	-
```

I used the same command on the three samples, also i get a huge difference in the amount of STR in the output: proband and mother have more than 6 million STR, while the father only has 458; the bam coverage is around 90X for all samples. Should I re-run the analyses? maybe something went wrong even if I did not get any warnings.

**Comment by readmanchiu** [comment]
hmmm...`father.tsv`, `mother.tsv`, and `proband.tsv` should be the tsv outputs of `straglr`, while `proband_vs_parent.tsv` should be the output of `straglr_compare.py`
what you showed in how you ran `straglr_compare.py` looks correct, but the lines showing after you `head father.tsv` looks like the output of `straglr_compare.py` instead of `straglr.py`, sorry I'm confused...

I am just wondering if your straglr tsv outputs have 15 columns, not the outputs of `straglr_compare.py`

also I would advise at least `2` for `--min_support` when you ran `straglr.py`

**Comment by readmanchiu** [comment]
Hi @gspirito,  have you been able to resolve this?

**Comment by readmanchiu** [comment]
I assumed the issue is resolved and will close the ticket.
Let me know if there is further issues.
