### ISSUE TITLE
Straglr could not find some TR that clearly existed

### ISSUE THREAD

**Issue by LiShuhang-gif** [bcgsc/straglr#3]
Hi, I'm using Straglr to detect TR based on my PacBio HiFi data. My parameters are shown below:

```
straglr.py M1.sort.filter.bam hg38_22_XYM.fa straglr_scan_min_ins50.tsv \
 --min_ins_size 50 \
 --genotype_in_size \
 --max_num_clusters 2 \
 --min_support 2 \
 --nprocs 23
```

However, I found that there were some TR that I could clearly see on igV that I couldn't find with Straglr, and I wondered if I was setting the parameters incorrectly.I set the insert length to be greater than 50bp and need two reads to support it, but I think the insert sequence meets both conditions.

![微信图片编辑_20211028100525](https://user-images.githubusercontent.com/82559149/139173710-9c063eb2-924c-4527-b436-bc0d182f09df.jpg)

As shown in the figure, there is a tandem repeat expansion exists in both C1 and M1 and is greater than 50bp supported by 2 or more reads. Oddly, I was able to find the this tandem repeat expansion with Straglr in C1, but not in M1. I wonder why? Is there any way to improve it? Do you have any suggestions?Thank you very much!

**Comment by LiShuhang-gif** [comment]
Thank you for your reply. In fact, Figure 2 I show is the result of C1, and this range of tandem repeat is not found in M1. I will post the results of all reads of both C1 and M1 in this region in order to investigate further.

C1:

![image](https://user-images.githubusercontent.com/82559149/139518143-34d6cb19-5ab3-4da6-ac99-3eb5b1a33ed9.png)

M1: (The tandem repeat region which I show above in C1 is not reported in M1, but can be observed in M1 through igv)

![image](https://user-images.githubusercontent.com/82559149/139518503-9e75502e-5564-44a3-a025-db7243926684.png)

As shown in the figure, in the result of M1, the coordinate jumped directly from chr11:1095111 to chr11:1097413.

**Comment by readmanchiu** [comment]
This is a difficult region with many complex tandem repeats. At this point, I can only do a better assessment if I can take a look at the sequences. I have put my email address above if you have no problem sending me the sequences to look at.

**Comment by LiShuhang-gif** [comment]
Hi, sorry for my late reply. I have already sent the problematic sequence of C1 and M1 that I mentioned above to your email address. Thank you for your help.  If there is any progress,  please feel free to contact me at any time. I will reply as soon as possible.

**Comment by readmanchiu** [comment]
Hi @LiShuhang-gif 
I've e-mailed the results back to you. It seems to me the insertions are captured in the results, please double check.
As I said, the region is populated with complex repeats. Reads seem to contain multiple insertions/expansions. The repeats reported may also not be "as expected". 
The commands used to generate the results:
```
python straglr.py c1_chr11_1096542-1096744.bam hg38.fa c1.tsv --min_str_len 2 --max_str_len 100 --min_ins_size 50 --genotype_in_size --min_support 2
python straglr.py m1_chr11_1096542-1096744.bam hg38.fa m1.tsv --min_str_len 2 --max_str_len 100 --min_ins_size 50 --genotype_in_size --min_support 2
```
The code used is the latest in the repository, which I haven't tagged yet for a new release because I'm still doing some testing.
Let me know if you have further questions.

**Comment by LiShuhang-gif** [comment]
Hi, Thank you for your prompt reply. I have tried your parameter setting. Indeed, the insertions are captured in the results. 
After comparing our parameter setting, the main difference I found was that I have set ```--max_num_clusters 2```. And obviously, as shown below, in the M1 sample, the insertion which I could not find according to my parameter setting, while could be found according to your parameter setting were clustered into 3 categories (as shown in column 5).

```
chr11	1096551	1096744	CA	2910.4(31);1748.3(3);244.5(8)	m64061_210711_093307/168888103/ccs	1459.0	2918	9914	2910.4
chr11	1096551	1096744	CA	2910.4(31);1748.3(3);244.5(8)	m64061_210711_093307/122422002/ccs	1459.0	2918	5999	2910.4
chr11	1096551	1096744	CA	2910.4(31);1748.3(3);244.5(8)	m64061_210711_093307/79824312/ccs	1458.5	2917	9093	2910.4
```

I wonder if it is because I have set this clustering parameter, but the results of these loci cannot be clustered into 2 categories, so they have been removed from the results of M1? Thank you very much!

**Comment by readmanchiu** [comment]
setting `--max_num_clusters 2` only forces the 3 1.7kb reads to be grouped with the 2.9kb ones, and subsequently decreases the reported size of the big allele from 2.9 to 2.8 kb. Overall, changing the number of clusters shouldn't really affect the number of supporting reads reported but it will change the genotype as the number of alleles, a result of clustering, might have changed.

**Comment by LiShuhang-gif** [comment]
Ok, thank you for your timely help. I have no further questions for the time being.
