### ISSUE TITLE
VCF output for hetrozygotes seems to be have incorrect GT's

### ISSUE THREAD

**Issue by bartcharbon** [bcgsc/straglr#39]
Hi @readmanchiu

Thanks again for implementing the VCF output!

Unfortunatly I run into an issue with the GTs for hetrozygotes:
I seem to get two VCF lines in these cases, of which one has a 0/0 GT and the other a 1/1 GT.

I would expect:
- a single line with a 1/2 call if there are 2 variants
- a single line with a 1/0 call if there is one variant STR and one reference STR
or alternatively
- two lines with a 1/0 GT if there are 2 variants

**Comment by readmanchiu** [comment]
Hmmm...that's interesting, my test cases all have one locus (chrom, start, end) per line.
Is it ok for you to share the error?

**Comment by bartcharbon** [comment]
Unfortunatly my current data is patient data I cannot share. 

I will try to reproduce the issue with public data.

**Comment by bartcharbon** [comment]
I attached the output of a Genome-in-a-bottle sample. (vcf file is zipped because otherwise github rejects the file)

The variant on chr13:70139353 illustrates the issue, there are two lines for this position, the first displaying a 1/1 GT and the second a 0/0.

[test.zip](https://github.com/user-attachments/files/15899389/test.zip)

**Comment by readmanchiu** [comment]
hmmm...the 2 lines actually have 2 different `POS` for the ATXN8OS locus, one at 70139353 and the other at 70139383
so it seems like it may not be a bug of the vcf output but something wrong with the genotyping.
Do you also have 70139353 and 70139383 in the TSV output?
I can double-check on my end to see if I can reproduce the error on ATXN8OS, but can you also check the ATXN8OS in the bed file you provided for the run (I assume you're running the genotyping mode)

**Comment by bartcharbon** [comment]
Hi @readmanchiu 

Sorry, I guess the error is on my side, I'll have a look at the original test with some patient data, but probably I just missed the differences in the positions there as well.

I'll close this for now.
