### ISSUE TITLE
Vcf does not get generated on Straglr version 1.5.0

### ISSUE THREAD

**Issue by zaka-edd** [bcgsc/straglr#45]
Hi,

I am encoutering an error while trying to run straglr, that causes no vcf file to be generated:
```Traceback (most recent call last):
  File "/home/zeddafir/miniforge3/envs/straglr/bin/straglr.py", line 101, in <module>
    main()
  File "/home/zeddafir/miniforge3/envs/straglr/bin/straglr.py", line 98, in main
    tre_finder.output_vcf(variants, '{}.vcf'.format(args.out_prefix))
  File "/home/zeddafir/miniforge3/envs/straglr/lib/python3.12/site-packages/src/tre.py", line 1513, in output_vcf
    fails = Variant.find_fails(variants)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeddafir/miniforge3/envs/straglr/lib/python3.12/site-packages/src/variant.py", line 244, in find_fails
    failed_reason = Counter(failed_reasons).most_common(1)[0][0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
The bed file and tsv file seem to be generated normally without any errors. I tried running a debug to see if I could find anything, but I was not able to figure out the problem. Do you have any suggestions on what could be causing the error?
[debug.log.gz](https://github.com/user-attachments/files/16691700/debug.log.gz)

The command I ran is:
```
straglr.py HG002_PacBio_HiFi_chr21.bam chr21.fa straglr_output --loci HG002_straglr.bed --min_support 2 --min_cluster_size 2
```

**Comment by readmanchiu** [comment]
Could you please try v1.5.1? The issue was tackled in this newest release and hopefully it will solve the problem. Thanks

**Comment by zaka-edd** [comment]
I will try that thank you :)
