### ISSUE TITLE
Genotyping mononucleotide repeats

### ISSUE THREAD

**Issue by 18parkky** [bcgsc/straglr#53]
Dear readmanchiu

Hello, thank you for developing Straglr. I read many papers that used Straglr for their repeat-expansion related research and it was nice to see that it worked very well. 

I am currently developing a lightweight Python package that estimates STR allele size from sequencing data, and I am trying to benchmark as many tool as possible, focusing on mononucleotide and dinucleotide repeats. While I can get Straglr to work nicely with dinucleotide repeats, mononucleotide repeats don't seem to work well. 

Specifically, in the output .bed file, the 'repeat_unit' column does not match with the repeat units I have specified in the `--loci` parameter. I am using mononucleotide STR with lengths varying from 10~15. 

I have noticed that your paper defines STR as 'typically composed of 2–6 base pair (bp) units repeated in tandem': does this mean Straglr do not support mononucleotide repeats? For your information, here are the first 3 rows in my `--loci` bed file.

chr3_MATERNAL	124491946	124491956	T
chr7_MATERNAL	83685092	83685102	T
chr18_MATERNAL	26944054	26944064	T

Thank you :) 

Sincerely, Gyumin

**Comment by readmanchiu** [comment]
Thanks for your interest in Straglr, @18parkky 
Unfortunately Straglr does not handle mononucleotide repeats. Such decision is made because it's very hard to distinguish signal vs errors when it comes to homopolymer lengths in nanopore sequencing reads.
I am also not aware of any pathogenic mononucleotide expansions, another reason we skip the 1bp repeats

**Comment by 18parkky** [comment]
Indeed, despite recent updates in chemistries and flow-cells, ONT still suffers heavily when sequencing homopolymer regions.
Thank you for your prompt response, @readmanchiu.
