### ISSUE TITLE
tmp files are not removed

### ISSUE THREAD

**Issue by stfacc** [bcgsc/straglr#54]
It looks like temporary files in /tmp are not automatically removed after usage.

Since they are usually very big files (*.fa, *.dat, *.blastn) this can quickly become a disk space issue

**Comment by readmanchiu** [comment]
Wonder what version you are running? Unless `--debug` is specified, all the temporary files should be removed after the run

**Comment by stfacc** [comment]
Yes, I'm using `--debug`. Not a bug then. I can't find this behavior in the docs, though?

Thank you.

**Comment by readmanchiu** [comment]
Sorry about that, I will update the doc for the next release.
