### ISSUE TITLE
Conda release

### ISSUE THREAD

**Issue by davidebolo1993** [bcgsc/straglr#9]
Hi all, 

any chance we will see straglr on conda soon?
Thanks,

Davide

**Comment by readmanchiu** [comment]
sure we'll get it going and hopefully it'll be in BioConda soon

**Comment by readmanchiu** [comment]
actually Straglr v1.2.0 is in Bioconda already
```conda install -c bioconda straglr```

**Comment by davidebolo1993** [comment]
Thanks, I'm getting in touch on another point. Closing this one.
